### PR TITLE
Revise API

### PR DESCRIPTION
**Pull request by anandthakker**
Working on some revisions to the API to:

 - Expose a useful node module for programmatic use
 - Improve ergonomics for forward, reverse, and forward+reverse reprojections.
 - Consider replacing some of our CLI code w/ a combination of ndjson-cli and d3-geo-projection 
 - 'forward' and 'forward+reverse' correspond roughly to 'use with tippecanoe' and 'use as geojson' (the latter of which we didn't do in wapo, but would likely be useful in general) -- update the docs to reflect this.

### CODE REVIEW

**Comment by dereklieu** [comment]
This looks solid to me, see my comment in #5 regarding the third bullet point on how to proceed there.

**Comment by anandthakker** [comment]
@dereklieu I think this is ready for 👀 .
 - exposes `reproject(options, coordinates)`
 - brings as named projections all the projections provided by `d3-geo` and `de-geo-projection` that don't require a parameter
 - `dirty-reproject` CLI script (installed with `npm install -g`)
   - accepts `--forward`, `--reverse`, or both (with `--reverse` defaulting to `'mercator'`)

**Comment by anandthakker** [comment]
Decided not to go with the `d3-geo-projection` CLI scripts, because to make this convenient for web-map use, we want to have default translate/scale values set on each of the projections -- much easier to do that programmatically.

**Comment by dereklieu** [comment]
Sweet. Looks good. Merging.

**Pull request merged**
